import Head from 'next/head';
import { Nav, Main, WhatIDo, Projects, Certifications } from '../components';
import { Box, Flex, Stack } from '@mantine/core';
import React, { useCallback, useState } from 'react';

const Index = () => {
  const [section, setSection] = useState<number>(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Flex direction="row" bg="navy.9">
        <Box bg="primary">
          <Nav
            h="100vh"
            w="100px"
            pos="fixed"
            setSection={setSection}
          />
          <Stack
            align="center"
            justify="center"
            ml="100px"
            w="calc(100vw - 150px)"
          >
            <Main isVisible={section === 0} />
            <WhatIDo isVisible={section === 1} />
            <Projects isVisible={section === 2} />
            <Certifications isVisible={section === 3} />
          </Stack>
        </Box>
      </Flex>
    </>
  );
};

export default Index;
