import Head from 'next/head';
import { Nav, Main, WhatIDo } from '../components';
import { Flex, Stack } from '@mantine/core';

import React from 'react';

const Index = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.ico" />
    </Head>
    <Flex direction="row" sx={{backgroundColor: "#00113a"}}>
      <Nav />
      <Stack align="center" justify="center" sx={{width: 'calc(100% - 100px)', marginLeft: '100px'}}>
        <Main />
        <WhatIDo />
      </Stack>
    </Flex>
  </>
);

export default Index;
