import Head from 'next/head';
import {
  VerticalNav,
  HorizontalNav,
  Main,
  Projects,
  Certifications,
  Footer
} from '../components';
import { Container, MediaQuery, Stack } from '@mantine/core';
import React, { useState } from 'react';

const Index = () => {
  const [section, setSection] = useState<number>(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <Container fluid bg="primary" px={0}>
        <MediaQuery smallerThan="md" styles={{ display: 'none' }}>
          <VerticalNav setSection={setSection} />
        </MediaQuery>
        <MediaQuery largerThan="md" styles={{ display: 'none' }}>
          <HorizontalNav setSection={setSection} />
        </MediaQuery>

        <MediaQuery
          largerThan="md"
          styles={{
            '&.mantine-Stack-root': {
              marginLeft: '100px',
              width: 'calc(100vw - 150px)',
            },
          }}
        >
          <Stack align="center" justify="center" spacing={128}>
            <Main isVisible={section === 0} />
            <Projects isVisible={section === 2} />
            <Certifications isVisible={section === 3} />
          </Stack>
        </MediaQuery>
        <Footer />
      </Container>
    </>
  );
};

export default Index;
